//
//  ContentQuestion.swift
//  StoryCollectionKit
//
//  Represents an AI-generated question for the conversational flow.
//

import Foundation

/// A question generated by AI to extract story details from the user
public struct ContentQuestion: Sendable, Identifiable, Equatable, Hashable {
    public let id: String
    public let question: String
    public let placeholder: String

    public init(id: String, question: String, placeholder: String) {
        self.id = id
        self.question = question
        self.placeholder = placeholder
    }
}
