/**
 * Render a self-contained HTML trend dashboard from the snapshot history.
 * Dependency-free inline SVG sparklines per ad (spend, CPI, link-CTR over time).
 * Overwritten each run at marketing/ads-analytics/dashboard.html.
 */
import { promises as fs } from 'node:fs';
import path from 'node:path';
import { DATA_DIR } from './store.mjs';

const W = 280, H = 70, PAD = 6;

function sparkline(points, { color = '#E8966E', invert = false } = {}) {
  const vals = points.map((p) => p.v).filter((v) => Number.isFinite(v));
  if (vals.length < 2) return `<svg width="${W}" height="${H}"><text x="6" y="40" fill="#6D6357" font-size="12" font-family="monospace">not enough data</text></svg>`;
  const min = Math.min(...vals), max = Math.max(...vals);
  const span = max - min || 1;
  const n = points.length;
  const x = (i) => PAD + (i / (n - 1)) * (W - 2 * PAD);
  const y = (v) => {
    const t = (v - min) / span;
    return PAD + (invert ? t : 1 - t) * (H - 2 * PAD);
  };
  let d = '';
  points.forEach((p, i) => {
    if (!Number.isFinite(p.v)) return;
    d += `${d ? 'L' : 'M'}${x(i).toFixed(1)} ${y(p.v).toFixed(1)} `;
  });
  const last = points.filter((p) => Number.isFinite(p.v)).at(-1);
  return `<svg width="${W}" height="${H}" viewBox="0 0 ${W} ${H}">
    <path d="${d}" fill="none" stroke="${color}" stroke-width="2"/>
    <circle cx="${x(n - 1).toFixed(1)}" cy="${y(last.v).toFixed(1)}" r="3" fill="${color}"/>
  </svg>`;
}

const money = (n) => (n == null ? '—' : `A$${Number(n).toFixed(2)}`);
const pct = (n) => (n == null ? '—' : `${(n * 100).toFixed(2)}%`);

export function renderDashboard(history, campaign) {
  // collect ad ids across history
  const ids = [...new Set(history.flatMap((s) => (s.ads || []).map((a) => a.id)))];
  const adName = (id) => {
    for (let i = history.length - 1; i >= 0; i--) {
      const a = (history[i].ads || []).find((x) => x.id === id);
      if (a) return a.name;
    }
    return id;
  };
  const seriesOf = (id, key) =>
    history.map((s) => {
      const a = (s.ads || []).find((x) => x.id === id);
      return { ts: s.ts, v: a ? a[key] : null };
    });

  const cards = ids
    .map((id) => {
      const latest = [...history].reverse().find((s) => (s.ads || []).some((a) => a.id === id));
      const a = latest?.ads.find((x) => x.id === id) || {};
      return `<div class="card">
      <h3>${adName(id)}</h3>
      <div class="now">${money(a.cpi)} CPI · ${a.installs ?? 0} installs · ${pct(a.linkCtr)} CTR · A$${Number(a.spend || 0).toFixed(2)} spent</div>
      <div class="charts">
        <div><span>Spend</span>${sparkline(seriesOf(id, 'spend'), { color: '#7FB069' })}</div>
        <div><span>CPI (lower better)</span>${sparkline(seriesOf(id, 'cpi'), { color: '#E8966E', invert: true })}</div>
        <div><span>Link CTR</span>${sparkline(seriesOf(id, 'linkCtr'), { color: '#6EA8E8' })}</div>
      </div>
    </div>`;
    })
    .join('\n');

  return `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Porizo Ads — ${campaign?.name || ''}</title>
<style>
  body{background:#15120E;color:#F6EFE3;font-family:-apple-system,system-ui,sans-serif;margin:0;padding:40px;}
  h1{font-size:26px;margin:0 0 4px;} .sub{color:#A89A88;font-size:14px;margin-bottom:32px;font-family:ui-monospace,monospace;}
  .grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(320px,1fr));gap:24px;}
  .card{background:#1A0F08;border:1px solid #2A221B;border-radius:14px;padding:20px;}
  .card h3{margin:0 0 6px;font-size:17px;}
  .now{color:#A89A88;font-size:13px;font-family:ui-monospace,monospace;margin-bottom:14px;}
  .charts>div{margin-bottom:10px;} .charts span{display:block;font-size:11px;color:#6D6357;text-transform:uppercase;letter-spacing:1px;margin-bottom:2px;}
  footer{margin-top:36px;color:#6D6357;font-size:12px;font-family:ui-monospace,monospace;}
</style></head><body>
<h1>${campaign?.name || 'Meta Ads'}</h1>
<div class="sub">campaign ${campaign?.id || ''} · ${history.length} snapshot(s) · updated ${history.at(-1)?.ts || '—'}</div>
<div class="grid">${cards || '<p>No snapshots yet.</p>'}</div>
<footer>Recommend-only analytics · generated by scripts/ads/run.mjs · CPI charts are inverted (down = improving)</footer>
</body></html>`;
}

export async function writeDashboard(html) {
  await fs.mkdir(DATA_DIR, { recursive: true });
  const file = path.join(DATA_DIR, 'dashboard.html');
  await fs.writeFile(file, html);
  return file;
}
