ALTER TABLE jobs ADD COLUMN IF NOT EXISTS error_code TEXT;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS error_message TEXT;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS next_attempt_at TEXT;

ALTER TABLE enrollment_sessions ADD COLUMN IF NOT EXISTS access_token TEXT;
ALTER TABLE track_versions ADD COLUMN IF NOT EXISTS guide_access_token TEXT;
