ALTER TABLE jobs ADD COLUMN IF NOT EXISTS progress_pct INTEGER;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS started_at TEXT;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS completed_at TEXT;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS last_heartbeat_at TEXT;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS external_task_id TEXT;

ALTER TABLE track_versions ADD COLUMN IF NOT EXISTS preview_job_id TEXT;
ALTER TABLE track_versions ADD COLUMN IF NOT EXISTS full_job_id TEXT;
