//
//  SharedModels.swift
//  PorizoApp
//
//  Common models used across multiple domains.
//  All types conform to Sendable for Swift 6 actor isolation.
//

import Foundation

// MARK: - Error Models

/// API error response
struct APIError: Codable, Error, Sendable {
    let error: String
    let message: String
    let details: [String: String]?
}

// MARK: - Memory Questions Models

/// A question generated by AI for extracting memory details
struct MemoryQuestion: Codable, Identifiable, Sendable {
    let id: String
    let question: String
    let placeholder: String
}

/// Response from POST /memory/questions
struct MemoryQuestionsResponse: Codable, Sendable {
    let questions: [MemoryQuestion]
}

/// Request body for POST /memory/questions
struct MemoryQuestionsRequest: Encodable, Sendable {
    let memory: String
    let occasion: String?
    let recipientName: String?

    enum CodingKeys: String, CodingKey {
        case memory, occasion
        case recipientName = "recipient_name"
    }
}

/// User's answer to an AI-generated memory question
struct MemoryAnswer: Codable, Sendable {
    let questionId: String
    let question: String
    let answer: String

    enum CodingKeys: String, CodingKey {
        case questionId = "question_id"
        case question, answer
    }
}

// MARK: - Speech Transcription Models

/// Response from POST /v2/story/:id/audio
struct SpeechTranscriptionResponse: Codable, Sendable {
    let success: Bool
    let transcription: String
    let language: String?
    let duration: Double?
    let textLength: Int?
    let storyStartWarningThreshold: Int?
    let storyStartLimit: Int?
    let exceedsStoryStartLimit: Bool?

    enum CodingKeys: String, CodingKey {
        case success
        case transcription
        case language
        case duration
        case textLength = "text_length"
        case storyStartWarningThreshold = "story_start_warning_threshold"
        case storyStartLimit = "story_start_limit"
        case exceedsStoryStartLimit = "exceeds_story_start_limit"
    }
}

// MARK: - OG Variant Preview Models

/// Individual OG variant preview item returned by preview endpoints.
struct OgVariantPreview: Codable, Identifiable, Sendable {
    let name: String
    let label: String
    let preview: String

    var id: String { name }
}

/// Shared response shape for song/poem OG preview lists.
struct OgVariantPreviewListResponse: Codable, Sendable {
    let currentVariant: String?
    let variants: [OgVariantPreview]

    enum CodingKeys: String, CodingKey {
        case currentVariant = "current_variant"
        case variants
    }
}
