//
//  Models.swift
//  PorizoApp
//
//  API response types matching the Node.js backend.
//  All types conform to Sendable for Swift 6 actor isolation.
//

import Foundation

// MARK: - Enrollment Models

/// Response from POST /voice/enrollment/start
struct EnrollmentSession: Codable, Sendable {
    let sessionId: String
    let sessionExpiresAt: String
    let prompts: [EnrollmentPrompt]?
    let promptSetId: String?
    let recordingSettings: RecordingSettings?

    enum CodingKeys: String, CodingKey {
        case sessionId = "session_id"
        case sessionExpiresAt = "session_expires_at"
        case prompts
        case promptSetId = "prompt_set_id"
        case recordingSettings = "recording_settings"
    }
}

/// Recording settings from backend
struct RecordingSettings: Codable, Sendable {
    let sampleRate: Int
    let channels: Int
    let format: String
    let maxChunkDurationSec: Int?

    enum CodingKeys: String, CodingKey {
        case sampleRate = "sample_rate"
        case channels
        case format
        case maxChunkDurationSec = "max_chunk_duration_sec"
    }
}

/// Voice enrollment prompt
struct EnrollmentPrompt: Codable, Sendable {
    let id: String
    let text: String
    let type: String  // "spoken" or "sung"
    let durationHintSec: Int?
    let pitchHint: String?

    enum CodingKeys: String, CodingKey {
        case id, text, type
        case durationHintSec = "duration_hint_sec"
        case pitchHint = "pitch_hint"
    }
}

/// Response from POST /debug/upload-chunk
struct ChunkUploadResponse: Codable, Sendable {
    let status: String  // "accepted"
    let chunkId: String
    let durationSec: Double

    enum CodingKeys: String, CodingKey {
        case status
        case chunkId = "chunk_id"
        case durationSec = "duration_sec"
    }
}

/// Response from POST /voice/enrollment/complete
struct VoiceProfile: Codable, Sendable {
    let voiceProfileId: String
    let qualityScore: Double?  // Backend returns float, not int
    let status: String
    let jobId: String?
    let estimatedCompletionSec: Int?

    enum CodingKeys: String, CodingKey {
        case voiceProfileId = "voice_profile_id"
        case qualityScore = "quality_score"
        case status
        case jobId = "job_id"
        case estimatedCompletionSec = "estimated_completion_sec"
    }
}

/// Response from GET /voice/profile
struct VoiceProfileStatus: Codable, Sendable {
    let profileId: String?
    let status: String?
    let qualityScore: Double?
    let createdAt: String?

    /// Computed property - has active profile if status is "active"
    var hasProfile: Bool {
        status == "active"
    }

    enum CodingKeys: String, CodingKey {
        case profileId = "profile_id"
        case status
        case qualityScore = "quality_score"
        case createdAt = "created_at"
    }
}

// MARK: - Error Models

/// API error response
struct APIError: Codable, Error, Sendable {
    let error: String
    let message: String
    let details: [String: String]?
}

// MARK: - App State

/// Local enrollment state for tracking progress
enum EnrollmentState {
    case notStarted
    case recording(prompt: String, type: PromptType)
    case uploading
    case processing
    case completed(qualityScore: Int)
    case failed(error: String)
}

enum PromptType: String {
    case spoken = "spoken"
    case sung = "sung"
}

/// Chunk tracking for upload progress
struct RecordedChunk {
    let id: String
    let type: PromptType
    let audioURL: URL
    let duration: TimeInterval
    var uploaded: Bool = false
}

// MARK: - Memory Questions Models

/// A question generated by AI for extracting memory details
struct MemoryQuestion: Codable, Identifiable, Sendable {
    let id: String
    let question: String
    let placeholder: String
}

/// Response from POST /memory/questions
struct MemoryQuestionsResponse: Codable, Sendable {
    let questions: [MemoryQuestion]
}

/// Request body for POST /memory/questions
struct MemoryQuestionsRequest: Encodable, Sendable {
    let memory: String
    let occasion: String?
    let recipientName: String?

    enum CodingKeys: String, CodingKey {
        case memory, occasion
        case recipientName = "recipient_name"
    }
}

/// User's answer to an AI-generated memory question
struct MemoryAnswer: Codable, Sendable {
    let questionId: String
    let question: String
    let answer: String

    enum CodingKeys: String, CodingKey {
        case questionId = "question_id"
        case question, answer
    }
}

// MARK: - Track Models

/// Request body for POST /tracks
struct CreateTrackRequest: Encodable, Sendable {
    let title: String
    let occasion: String
    let recipientName: String
    let style: String
    let durationTarget: Int
    let voiceMode: String
    let message: String
    // Story context from wizard
    let specificMemory: String?
    let memoryAnswers: [MemoryAnswer]?
    let specialPhrases: String?
    let whatMakesThemSpecial: String?
    // Legacy fields (kept for compatibility)
    let relationshipType: String?
    let yearsKnown: Int?

    enum CodingKeys: String, CodingKey {
        case title, occasion, style, message
        case recipientName = "recipient_name"
        case durationTarget = "duration_target"
        case voiceMode = "voice_mode"
        case specificMemory = "specific_memory"
        case memoryAnswers = "memory_answers"
        case specialPhrases = "special_phrases"
        case whatMakesThemSpecial = "what_makes_them_special"
        case relationshipType = "relationship_type"
        case yearsKnown = "years_known"
    }
}

/// Response from POST /tracks
struct CreateTrackResponse: Codable, Sendable {
    let trackId: String
    let status: String

    enum CodingKeys: String, CodingKey {
        case trackId = "track_id"
        case status
    }
}

/// Response from POST /tracks/:id/versions
struct CreateVersionResponse: Codable, Sendable {
    let trackVersionId: String
    let versionNum: Int
    let status: String

    enum CodingKeys: String, CodingKey {
        case trackVersionId = "track_version_id"
        case versionNum = "version_num"
        case status
    }
}

/// A track from the backend
struct Track: Codable, Sendable {
    let id: String
    let userId: String
    let title: String
    let occasion: String?
    let recipientName: String?
    let style: String?
    let durationTarget: Int?
    let voiceMode: String?
    let message: String?
    let status: String
    let latestVersion: Int
    let shareTokenId: String?
    let createdAt: String
    let updatedAt: String

    enum CodingKeys: String, CodingKey {
        case id
        case userId = "user_id"
        case title, occasion, style, message, status
        case recipientName = "recipient_name"
        case durationTarget = "duration_target"
        case voiceMode = "voice_mode"
        case latestVersion = "latest_version"
        case shareTokenId = "share_token_id"
        case createdAt = "created_at"
        case updatedAt = "updated_at"
    }
}

/// A track version from the backend
struct TrackVersion: Codable, Sendable {
    let id: String
    let trackId: String
    let versionNum: Int
    let status: String
    let renderType: String?
    let lyricsStatus: String?
    let lyricsJson: String?
    let previewUrl: String?
    let fullUrl: String?
    let moderationStatus: String?
    let moderationReason: String?
    let createdAt: String
    let completedAt: String?

    enum CodingKeys: String, CodingKey {
        case id, status
        case trackId = "track_id"
        case versionNum = "version_num"
        case renderType = "render_type"
        case lyricsStatus = "lyrics_status"
        case lyricsJson = "lyrics_json"
        case previewUrl = "preview_url"
        case fullUrl = "full_url"
        case moderationStatus = "moderation_status"
        case moderationReason = "moderation_reason"
        case createdAt = "created_at"
        case completedAt = "completed_at"
    }
}

/// Response from GET /tracks/:id
struct GetTrackResponse: Codable, Sendable {
    let track: Track
    let versions: [TrackVersion]
}

/// Response from GET /tracks
struct GetTracksResponse: Codable, Sendable {
    let tracks: [Track]
}

/// Lyrics structure from the backend
struct Lyrics: Codable, Sendable {
    let title: String?
    let style: String?
    let sections: [LyricsSection]
    let anchorLine: String?

    enum CodingKeys: String, CodingKey {
        case title, style, sections
        case anchorLine = "anchor_line"
    }
}

/// A section of lyrics (verse, chorus, etc.)
struct LyricsSection: Codable, Sendable {
    let name: String
    let lines: [String]
}

/// Response from POST /tracks/:id/versions/:version/lyrics/generate
struct GenerateLyricsResponse: Codable, Sendable {
    let lyrics: Lyrics?
    let lyricsStatus: String?
    let fallbackReason: String?

    enum CodingKeys: String, CodingKey {
        case lyrics
        case lyricsStatus = "lyrics_status"
        case fallbackReason = "fallback_reason"
    }
}

/// Response from POST /tracks/:id/versions/:version/lyrics/approve
struct ApproveLyricsResponse: Codable, Sendable {
    let approved: Bool
    let lyricsStatus: String?

    enum CodingKeys: String, CodingKey {
        case approved
        case lyricsStatus = "lyrics_status"
    }
}

/// Response from POST /tracks/:id/versions/:version/render_preview
struct RenderPreviewResponse: Codable, Sendable {
    let jobId: String?
    let estimatedCompletionSec: Int?
    let pollUrl: String?

    enum CodingKeys: String, CodingKey {
        case jobId = "job_id"
        case estimatedCompletionSec = "estimated_completion_sec"
        case pollUrl = "poll_url"
    }
}

/// Job status from GET /jobs/:id
struct JobStatus: Codable, Sendable {
    let id: String
    let status: String  // queued, processing, completed, failed
    let progress: Int?
    let resultUrl: String?
    let errorCode: String?
    let errorMessage: String?

    enum CodingKeys: String, CodingKey {
        case id, status, progress
        case resultUrl = "result_url"
        case errorCode = "error_code"
        case errorMessage = "error_message"
    }
}

// MARK: - Music Styles

/// Available music styles
enum MusicStyle: String, CaseIterable, Identifiable {
    // Popular
    case pop = "pop"
    case acoustic = "acoustic"
    case soul = "soul"
    case folk = "folk"
    case jazz = "jazz"
    case rnb = "rnb"
    case rock = "rock"
    case country = "country"

    // African
    case afrobeats = "afrobeats"
    case highlife = "highlife"
    case afropop = "afropop"

    // Latin
    case reggaeton = "reggaeton"
    case salsa = "salsa"
    case bossaNova = "bossa_nova"
    case bachata = "bachata"
    case latinPop = "latin_pop"

    var id: String { rawValue }

    var displayName: String {
        switch self {
        case .pop: return "Pop"
        case .acoustic: return "Acoustic"
        case .soul: return "Soul"
        case .folk: return "Folk"
        case .jazz: return "Jazz"
        case .rnb: return "R&B"
        case .rock: return "Rock"
        case .country: return "Country"
        case .afrobeats: return "Afrobeats"
        case .highlife: return "Highlife"
        case .afropop: return "Afropop"
        case .reggaeton: return "Reggaeton"
        case .salsa: return "Salsa"
        case .bossaNova: return "Bossa Nova"
        case .bachata: return "Bachata"
        case .latinPop: return "Latin Pop"
        }
    }
}

/// Available occasions
enum Occasion: String, CaseIterable, Identifiable {
    case birthday = "birthday"
    case anniversary = "anniversary"
    case thankYou = "thank_you"
    case iLoveYou = "i_love_you"
    case wedding = "wedding"
    case graduation = "graduation"
    case celebration = "celebration"
    case apology = "apology"
    case encouragement = "encouragement"
    case custom = "custom"

    var id: String { rawValue }

    var displayName: String {
        switch self {
        case .birthday: return "Birthday"
        case .anniversary: return "Anniversary"
        case .thankYou: return "Thank You"
        case .iLoveYou: return "I Love You"
        case .wedding: return "Wedding"
        case .graduation: return "Graduation"
        case .celebration: return "Celebration"
        case .apology: return "Apology"
        case .encouragement: return "Encouragement"
        case .custom: return "Custom"
        }
    }

    var emoji: String {
        switch self {
        case .birthday: return "🎂"
        case .anniversary: return "💑"
        case .thankYou: return "🙏"
        case .iLoveYou: return "❤️"
        case .wedding: return "💒"
        case .graduation: return "🎓"
        case .celebration: return "🎉"
        case .apology: return "💐"
        case .encouragement: return "💪"
        case .custom: return "✨"
        }
    }
}
