//
//  Models.swift
//  PorizoApp
//
//  API response types matching the Node.js backend.
//  All types conform to Sendable for Swift 6 actor isolation.
//

import Foundation

// MARK: - Enrollment Models

/// Response from POST /voice/enrollment/start
struct EnrollmentSession: Codable, Sendable {
    let sessionId: String
    let sessionExpiresAt: String
    let prompts: [EnrollmentPrompt]?
    let promptSetId: String?
    let uploadUrls: [UploadURL]?
    let recordingSettings: RecordingSettings?

    enum CodingKeys: String, CodingKey {
        case sessionId = "session_id"
        case sessionExpiresAt = "session_expires_at"
        case prompts
        case promptSetId = "prompt_set_id"
        case uploadUrls = "upload_urls"
        case recordingSettings = "recording_settings"
    }
}

/// Presigned upload URL for enrollment chunks
struct UploadURL: Codable, Sendable {
    let chunkId: String
    let url: String
    let method: String?
    let headers: [String: String]?
    let expiresAt: String?

    enum CodingKeys: String, CodingKey {
        case chunkId = "chunk_id"
        case url
        case method
        case headers
        case expiresAt = "expires_at"
    }
}

/// Recording settings from backend
struct RecordingSettings: Codable, Sendable {
    let sampleRate: Int
    let channels: Int
    let format: String
    let maxChunkDurationSec: Int?

    enum CodingKeys: String, CodingKey {
        case sampleRate = "sample_rate"
        case channels
        case format
        case maxChunkDurationSec = "max_chunk_duration_sec"
    }
}

/// Voice enrollment prompt
struct EnrollmentPrompt: Codable, Sendable {
    let id: String
    let text: String
    let type: String  // "spoken" or "sung"
    let durationHintSec: Int?
    let pitchHint: String?

    enum CodingKeys: String, CodingKey {
        case id, text, type
        case durationHintSec = "duration_hint_sec"
        case pitchHint = "pitch_hint"
    }
}

/// Response from POST /debug/upload-chunk
struct ChunkUploadResponse: Codable, Sendable {
    let status: String  // "accepted"
    let qcJobId: String?
    let nextUploadUrl: UploadURL?
    let chunkId: String?
    let durationSec: Double?

    enum CodingKeys: String, CodingKey {
        case status
        case qcJobId = "qc_job_id"
        case nextUploadUrl = "next_upload_url"
        case chunkId = "chunk_id"
        case durationSec = "duration_sec"
    }
}

/// Response from POST /voice/enrollment/complete
struct VoiceProfile: Codable, Sendable {
    let voiceProfileId: String
    let qualityScore: Double?  // Backend returns float, not int
    let status: String
    let jobId: String?
    let estimatedCompletionSec: Int?

    enum CodingKeys: String, CodingKey {
        case voiceProfileId = "voice_profile_id"
        case qualityScore = "quality_score"
        case status
        case jobId = "job_id"
        case estimatedCompletionSec = "estimated_completion_sec"
    }
}

/// Response from GET /voice/profile
struct VoiceProfileStatus: Codable, Sendable {
    let profileId: String?
    let status: String?
    let qualityScore: Double?
    let createdAt: String?

    /// Computed property - has active profile if status is "active"
    var hasProfile: Bool {
        status == "active"
    }

    enum CodingKeys: String, CodingKey {
        case profileId = "profile_id"
        case status
        case qualityScore = "quality_score"
        case createdAt = "created_at"
    }
}

// MARK: - Error Models

/// API error response
struct APIError: Codable, Error, Sendable {
    let error: String
    let message: String
    let details: [String: String]?
}

// MARK: - App State

/// Local enrollment state for tracking progress
enum EnrollmentState: Sendable {
    case notStarted
    case recording(prompt: String, type: PromptType)
    case uploading
    case processing
    case completed(qualityScore: Int)
    case failed(error: String)
}

enum PromptType: String, Sendable {
    case spoken = "spoken"
    case sung = "sung"
}

/// Chunk tracking for upload progress
struct RecordedChunk: Sendable {
    let id: String
    let type: PromptType
    let audioURL: URL
    let duration: TimeInterval
    var uploaded: Bool = false
}

// MARK: - Memory Questions Models

/// A question generated by AI for extracting memory details
struct MemoryQuestion: Codable, Identifiable, Sendable {
    let id: String
    let question: String
    let placeholder: String
}

/// Response from POST /memory/questions
struct MemoryQuestionsResponse: Codable, Sendable {
    let questions: [MemoryQuestion]
}

/// Request body for POST /memory/questions
struct MemoryQuestionsRequest: Encodable, Sendable {
    let memory: String
    let occasion: String?
    let recipientName: String?

    enum CodingKeys: String, CodingKey {
        case memory, occasion
        case recipientName = "recipient_name"
    }
}

/// User's answer to an AI-generated memory question
struct MemoryAnswer: Codable, Sendable {
    let questionId: String
    let question: String
    let answer: String

    enum CodingKeys: String, CodingKey {
        case questionId = "question_id"
        case question, answer
    }
}

// MARK: - Track Models

/// Request body for POST /tracks
struct CreateTrackRequest: Encodable, Sendable {
    let title: String
    let occasion: String
    let recipientName: String
    let style: String
    let durationTarget: Int
    let voiceMode: String
    let message: String
    // Story context from wizard
    let specificMemory: String?
    let memoryAnswers: [MemoryAnswer]?
    let specialPhrases: String?
    let whatMakesThemSpecial: String?
    // Legacy fields (kept for compatibility)
    let relationshipType: String?
    let yearsKnown: Int?

    enum CodingKeys: String, CodingKey {
        case title, occasion, style, message
        case recipientName = "recipient_name"
        case durationTarget = "duration_target"
        case voiceMode = "voice_mode"
        case specificMemory = "specific_memory"
        case memoryAnswers = "memory_answers"
        case specialPhrases = "special_phrases"
        case whatMakesThemSpecial = "what_makes_them_special"
        case relationshipType = "relationship_type"
        case yearsKnown = "years_known"
    }
}

/// Response from POST /tracks
struct CreateTrackResponse: Codable, Sendable {
    let trackId: String
    let status: String

    enum CodingKeys: String, CodingKey {
        case trackId = "track_id"
        case status
    }
}

/// Response from POST /tracks/:id/versions
struct CreateVersionResponse: Codable, Sendable {
    let trackVersionId: String
    let versionNum: Int
    let status: String

    enum CodingKeys: String, CodingKey {
        case trackVersionId = "track_version_id"
        case versionNum = "version_num"
        case status
    }
}

/// A track from the backend
struct Track: Codable, Sendable, Identifiable {
    let id: String
    let userId: String
    let title: String
    let occasion: String?
    let recipientName: String?
    let style: String?
    let durationTarget: Int?
    let voiceMode: String?
    let message: String?
    let status: String
    let latestVersion: Int
    let shareTokenId: String?
    let createdAt: String
    let updatedAt: String

    enum CodingKeys: String, CodingKey {
        case id
        case userId = "user_id"
        case title, occasion, style, message, status
        case recipientName = "recipient_name"
        case durationTarget = "duration_target"
        case voiceMode = "voice_mode"
        case latestVersion = "latest_version"
        case shareTokenId = "share_token_id"
        case createdAt = "created_at"
        case updatedAt = "updated_at"
    }
}

/// A track version from the backend
struct TrackVersion: Codable, Sendable {
    let id: String
    let trackId: String
    let versionNum: Int
    let status: String
    let renderType: String?
    let lyricsStatus: String?
    let lyricsJson: Lyrics?  // Changed from String? to Lyrics?
    let previewUrl: String?
    let fullUrl: String?
    let previewJobId: String?
    let fullJobId: String?
    let moderationStatus: String?
    let moderationReason: String?
    let createdAt: String
    let completedAt: String?

    enum CodingKeys: String, CodingKey {
        case id, status
        case trackId = "track_id"
        case versionNum = "version_num"
        case renderType = "render_type"
        case lyricsStatus = "lyrics_status"
        case lyricsJson = "lyrics_json"
        case previewUrl = "preview_url"
        case fullUrl = "full_url"
        case previewJobId = "preview_job_id"
        case fullJobId = "full_job_id"
        case moderationStatus = "moderation_status"
        case moderationReason = "moderation_reason"
        case createdAt = "created_at"
        case completedAt = "completed_at"
    }
}

/// Response from GET /tracks/:id
struct GetTrackResponse: Codable, Sendable {
    let track: Track
    let versions: [TrackVersion]
}

/// Response from GET /tracks
struct GetTracksResponse: Codable, Sendable {
    let tracks: [Track]
}

/// Lyrics structure from the backend
struct Lyrics: Codable, Sendable {
    let title: String?
    let style: String?
    let sections: [LyricsSection]
    let anchorLine: String?

    enum CodingKeys: String, CodingKey {
        case title, style, sections
        case anchorLine = "anchor_line"
    }
}

/// A section of lyrics (verse, chorus, etc.)
struct LyricsSection: Codable, Sendable {
    let name: String
    let lines: [String]
}

/// Response from POST /tracks/:id/versions/:version/lyrics/generate
struct GenerateLyricsResponse: Codable, Sendable {
    let lyrics: Lyrics?
    let lyricsStatus: String?
    let fallbackReason: String?

    enum CodingKeys: String, CodingKey {
        case lyrics
        case lyricsStatus = "lyrics_status"
        case fallbackReason = "fallback_reason"
    }
}

/// Response from POST /tracks/:id/versions/:version/lyrics/approve
struct ApproveLyricsResponse: Codable, Sendable {
    let approved: Bool
    let lyricsStatus: String?

    enum CodingKeys: String, CodingKey {
        case approved
        case lyricsStatus = "lyrics_status"
    }
}

/// Response from POST /tracks/:id/versions/:version/render_preview
struct RenderPreviewResponse: Codable, Sendable {
    let jobId: String?
    let estimatedCompletionSec: Int?
    let pollUrl: String?

    enum CodingKeys: String, CodingKey {
        case jobId = "job_id"
        case estimatedCompletionSec = "estimated_completion_sec"
        case pollUrl = "poll_url"
    }
}

/// Response from POST /tracks/:id/versions/:version/render_full
struct RenderFullResponse: Codable, Sendable {
    let jobId: String?
    let billingHoldId: String?
    let creditsReserved: Int?
    let estimatedCompletionSec: Int?

    enum CodingKeys: String, CodingKey {
        case jobId = "job_id"
        case billingHoldId = "billing_hold_id"
        case creditsReserved = "credits_reserved"
        case estimatedCompletionSec = "estimated_completion_sec"
    }
}

/// Response from GET /entitlements
struct EntitlementsResponse: Codable, Sendable {
    let entitlements: Entitlements?
    let riskLevel: String?

    enum CodingKeys: String, CodingKey {
        case entitlements
        case riskLevel = "risk_level"
    }
}

/// User entitlements (subscription limits)
struct Entitlements: Codable, Sendable {
    let userId: String?
    let tier: String  // "free", "basic", "pro"
    let creditsBalance: Int  // Songs remaining this period
    let creditsUsedTotal: Int  // Total songs ever created
    let previewCountToday: Int
    let previewCountResetAt: String?
    let updatedAt: String?
    // Subscription fields (optional, added for subscription model)
    let songsThisMonth: Int?
    let monthlyLimit: Int?
    let periodEndsAt: String?

    enum CodingKeys: String, CodingKey {
        case userId = "user_id"
        case tier
        case creditsBalance = "credits_balance"
        case creditsUsedTotal = "credits_used_total"
        case previewCountToday = "preview_count_today"
        case previewCountResetAt = "preview_count_reset_at"
        case updatedAt = "updated_at"
        case songsThisMonth = "songs_this_month"
        case monthlyLimit = "monthly_limit"
        case periodEndsAt = "period_ends_at"
    }

    /// Check if user has songs remaining this month
    var hasCredits: Bool {
        creditsBalance > 0
    }

    /// Check if user can create another song this month
    var canCreateSong: Bool {
        if let limit = monthlyLimit, let used = songsThisMonth {
            return used < limit
        }
        // Fall back to credits balance
        return creditsBalance > 0
    }

    /// Display text for remaining songs
    var remainingText: String {
        if let limit = monthlyLimit, let used = songsThisMonth {
            let remaining = max(0, limit - used)
            return "\(remaining) of \(limit) songs"
        }
        return "\(creditsBalance) songs"
    }
}

/// Job status from GET /jobs/:id
struct JobStatus: Codable, Sendable {
    let id: String
    let status: String  // queued, processing, completed, failed
    let progress: Int?
    let resultUrl: String?
    let errorCode: String?
    let errorMessage: String?
    let step: String?
    let stepIndex: Int?
    let workflowType: String?
    let startedAt: String?
    let completedAt: String?

    enum CodingKeys: String, CodingKey {
        case id, status, progress, step
        case resultUrl = "result_url"
        case errorCode = "error_code"
        case errorMessage = "error_message"
        case stepIndex = "step_index"
        case workflowType = "workflow_type"
        case startedAt = "started_at"
        case completedAt = "completed_at"
    }
}

// MARK: - Reroll Models

/// Types of reroll operations
/// - lyrics: Regenerate lyrics only (cheapest, reuses instrumental)
/// - beat: New genre/style, regenerate instrumental
/// - vocals: New prosody/similarity settings for voice conversion
enum RerollType: String, Codable, Sendable, CaseIterable {
    case lyrics = "lyrics"
    case beat = "beat"
    case vocals = "vocals"

    var displayName: String {
        switch self {
        case .lyrics: return "Lyrics"
        case .beat: return "Beat"
        case .vocals: return "Vocals"
        }
    }

    var description: String {
        switch self {
        case .lyrics: return "Generate new lyrics"
        case .beat: return "New instrumental style"
        case .vocals: return "New vocal performance"
        }
    }

    var iconName: String {
        switch self {
        case .lyrics: return "text.quote"
        case .beat: return "waveform"
        case .vocals: return "mic.fill"
        }
    }
}

/// Response from POST /tracks/:id/versions/:version/reroll
struct RerollResponse: Codable, Sendable {
    let newVersionNum: Int
    let jobId: String?
    let status: String
    let estimatedCompletionSec: Int?

    enum CodingKeys: String, CodingKey {
        case newVersionNum = "new_version_num"
        case jobId = "job_id"
        case status
        case estimatedCompletionSec = "estimated_completion_sec"
    }
}

// MARK: - Music Styles

/// Available music styles
enum MusicStyle: String, CaseIterable, Identifiable {
    // Popular
    case pop = "pop"
    case acoustic = "acoustic"
    case soul = "soul"
    case folk = "folk"
    case jazz = "jazz"
    case rnb = "rnb"
    case rock = "rock"
    case country = "country"

    // African
    case afrobeats = "afrobeats"
    case highlife = "highlife"
    case afropop = "afropop"

    // Latin
    case reggaeton = "reggaeton"
    case salsa = "salsa"
    case bossaNova = "bossa_nova"
    case bachata = "bachata"
    case latinPop = "latin_pop"

    var id: String { rawValue }

    var displayName: String {
        switch self {
        case .pop: return "Pop"
        case .acoustic: return "Acoustic"
        case .soul: return "Soul"
        case .folk: return "Folk"
        case .jazz: return "Jazz"
        case .rnb: return "R&B"
        case .rock: return "Rock"
        case .country: return "Country"
        case .afrobeats: return "Afrobeats"
        case .highlife: return "Highlife"
        case .afropop: return "Afropop"
        case .reggaeton: return "Reggaeton"
        case .salsa: return "Salsa"
        case .bossaNova: return "Bossa Nova"
        case .bachata: return "Bachata"
        case .latinPop: return "Latin Pop"
        }
    }
}

// MARK: - Poem Models

/// A poem created for a recipient
struct Poem: Codable, Sendable, Identifiable {
    let id: String
    let userId: String
    let title: String
    let recipientName: String
    let occasion: String
    let tone: String
    let status: String  // draft, complete
    let verses: [String]
    let createdAt: String
    let updatedAt: String

    enum CodingKeys: String, CodingKey {
        case id
        case userId = "user_id"
        case title
        case recipientName = "recipient_name"
        case occasion, tone, status, verses
        case createdAt = "created_at"
        case updatedAt = "updated_at"
    }

    /// Preview of poem (first 2 lines)
    var previewLines: String {
        verses.prefix(2).joined(separator: " ")
    }
}

/// Response from GET /poems
struct GetPoemsResponse: Codable, Sendable {
    let poems: [Poem]
}

/// Request body for POST /poems
struct CreatePoemRequest: Encodable, Sendable {
    let title: String
    let recipientName: String
    let occasion: String
    let tone: String
    let message: String
    let memoryAnswers: [MemoryAnswer]?

    enum CodingKeys: String, CodingKey {
        case title, occasion, tone, message
        case recipientName = "recipient_name"
        case memoryAnswers = "memory_answers"
    }
}

/// Available poem tones
enum PoemTone: String, CaseIterable, Identifiable {
    case heartfelt = "heartfelt"
    case playful = "playful"
    case formal = "formal"
    case poetic = "poetic"
    case simple = "simple"
    case rhyming = "rhyming"
    case freeVerse = "free_verse"

    var id: String { rawValue }

    var displayName: String {
        switch self {
        case .heartfelt: return "Heartfelt"
        case .playful: return "Playful"
        case .formal: return "Formal"
        case .poetic: return "Poetic"
        case .simple: return "Simple"
        case .rhyming: return "Rhyming"
        case .freeVerse: return "Free Verse"
        }
    }

    var description: String {
        switch self {
        case .heartfelt: return "Sincere and emotional"
        case .playful: return "Fun and lighthearted"
        case .formal: return "Elegant and traditional"
        case .poetic: return "Artistic and metaphorical"
        case .simple: return "Clear and direct"
        case .rhyming: return "Classic rhyme scheme"
        case .freeVerse: return "No fixed structure"
        }
    }
}

/// Response from GET /poems/:id
struct GetPoemResponse: Codable, Sendable {
    let poem: Poem
}

/// Request body for PUT /poems/:id
struct UpdatePoemRequest: Encodable, Sendable {
    let title: String?
    let tone: String?
    let verses: [String]?
    let status: String?

    init(title: String? = nil, tone: String? = nil, verses: [String]? = nil, status: String? = nil) {
        self.title = title
        self.tone = tone
        self.verses = verses
        self.status = status
    }
}

/// Response from PUT /poems/:id
struct UpdatePoemResponse: Codable, Sendable {
    let poem: Poem
}

// MARK: - Share Models

/// Response from POST /tracks/:id/share
struct CreateShareResponse: Codable, Sendable {
    let shareId: String
    let shareUrl: String
    let qrCodeUrl: String
    let expiresAt: String
    let claimPin: String  // 6-digit PIN to share with recipient

    enum CodingKeys: String, CodingKey {
        case shareId = "share_id"
        case shareUrl = "share_url"
        case qrCodeUrl = "qr_code_url"
        case expiresAt = "expires_at"
        case claimPin = "claim_pin"
    }
}

/// Share statistics from GET /tracks/:id/share/stats
struct ShareStats: Codable, Sendable {
    let shareId: String
    let status: String
    let expiresAt: String
    let createdAt: String
    let isExpired: Bool
    // Flattened fields (previously nested in access_stats/claim_info)
    let totalEvents: Int
    let eventCounts: [String: EventCount]?
    let isClaimed: Bool
    let boundDevice: BoundDeviceInfo?
    let recentActivity: [ActivityEntry]?

    enum CodingKeys: String, CodingKey {
        case shareId = "share_id"
        case status
        case expiresAt = "expires_at"
        case createdAt = "created_at"
        case isExpired = "is_expired"
        case totalEvents = "total_events"
        case eventCounts = "event_counts"
        case isClaimed = "is_claimed"
        case boundDevice = "bound_device"
        case recentActivity = "recent_activity"
    }

    struct EventCount: Codable, Sendable {
        let count: Int
        let lastAt: String?

        enum CodingKeys: String, CodingKey {
            case count
            case lastAt = "last_at"
        }
    }

    struct ActivityEntry: Codable, Sendable {
        let eventType: String
        let metadata: [String: String]?
        let createdAt: String

        enum CodingKeys: String, CodingKey {
            case eventType = "event_type"
            case metadata
            case createdAt = "created_at"
        }
    }

    struct BoundDeviceInfo: Codable, Sendable {
        let platform: String?
        let appVersion: String?
        let boundAt: String?

        enum CodingKeys: String, CodingKey {
            case platform
            case appVersion = "app_version"
            case boundAt = "bound_at"
        }
    }

    /// Check if share is revoked
    var isRevoked: Bool {
        status == "revoked"
    }

    /// Check if share is still valid (not expired and not revoked)
    var isValid: Bool {
        !isExpired && !isRevoked
    }
}

/// Response from DELETE /tracks/:id/share
struct RevokeShareResponse: Codable, Sendable {
    let revoked: Bool
}

/// QR code data URL response from GET /tracks/:id/share/qr-data
struct QRCodeDataResponse: Codable, Sendable {
    let shareUrl: String
    let qrDataUrl: String
    let size: Int

    enum CodingKeys: String, CodingKey {
        case shareUrl = "share_url"
        case qrDataUrl = "qr_data_url"
        case size
    }
}

/// Response from GET /share/:id
struct ShareInfoResponse: Codable, Sendable {
    let status: String
    let canAccess: Bool?
    let track: ShareTrackInfo?
    let trackPreview: ShareTrackInfo?
    let webStreamUrl: String?
    let appDownloadUrl: String?

    enum CodingKeys: String, CodingKey {
        case status
        case canAccess = "can_access"
        case track
        case trackPreview = "track_preview"
        case webStreamUrl = "web_stream_url"
        case appDownloadUrl = "app_download_url"
    }
}

struct ShareTrackInfo: Codable, Sendable {
    let title: String?
    let recipientName: String?
    let durationSec: Int?
    let coverImageUrl: String?

    enum CodingKeys: String, CodingKey {
        case title
        case recipientName = "recipient_name"
        case durationSec = "duration_sec"
        case coverImageUrl = "cover_image_url"
    }
}

/// Response from POST /share/:id/claim
struct ShareClaimResponse: Codable, Sendable {
    let status: String
    let appSaveAllowed: Bool?
    let expiresAt: String?

    enum CodingKeys: String, CodingKey {
        case status
        case appSaveAllowed = "app_save_allowed"
        case expiresAt = "expires_at"
    }
}

/// Response from GET /share/:id/stream
struct ShareStreamResponse: Codable, Sendable {
    let streamUrl: String
    let format: String?
    let keyUrl: String?
    let expiresAt: String?

    enum CodingKeys: String, CodingKey {
        case streamUrl = "stream_url"
        case format
        case keyUrl = "key_url"
        case expiresAt = "expires_at"
    }
}

// MARK: - Subscription Models

/// Response from POST /billing/receipt/apple
struct SyncReceiptResponse: Codable, Sendable {
    let success: Bool
    let subscription: SubscriptionInfo
    let entitlements: BillingEntitlements

    struct SubscriptionInfo: Codable, Sendable {
        let id: String
        let tier: String
        let status: String
        let songsGranted: Int
        let expiresAt: String?

        enum CodingKeys: String, CodingKey {
            case id, tier, status
            case songsGranted = "songs_granted"
            case expiresAt = "expires_at"
        }
    }
}

/// Response from GET /billing/entitlements
struct BillingEntitlements: Codable, Sendable {
    let tier: String
    let songsRemaining: Int
    let songsAllowance: Int
    let songsUsedTotal: Int
    let trialSongsRemaining: Int
    let trialExpiresAt: String?
    let previewCountToday: Int
    let planId: String?
    let billingPeriod: String?
    let subscriptionStartsAt: String?
    let subscriptionRenewsAt: String?
    let autoRenewEnabled: Bool?
    let isInGracePeriod: Bool?

    enum CodingKeys: String, CodingKey {
        case tier
        case songsRemaining = "songs_remaining"
        case songsAllowance = "songs_allowance"
        case songsUsedTotal = "songs_used_total"
        case trialSongsRemaining = "trial_songs_remaining"
        case trialExpiresAt = "trial_expires_at"
        case previewCountToday = "preview_count_today"
        case planId = "plan_id"
        case billingPeriod = "billing_period"
        case subscriptionStartsAt = "subscription_starts_at"
        case subscriptionRenewsAt = "subscription_renews_at"
        case autoRenewEnabled = "auto_renew_enabled"
        case isInGracePeriod = "is_in_grace_period"
    }

    /// Check if trial is active
    var isTrialActive: Bool {
        trialSongsRemaining > 0 && trialExpiresAt != nil
    }

    /// Parse trial expiration date
    var trialExpiresAtDate: Date? {
        guard let str = trialExpiresAt else { return nil }
        return ISO8601DateFormatter().date(from: str)
    }

    /// Parse subscription expiration date
    var subscriptionExpiresAtDate: Date? {
        guard let str = subscriptionRenewsAt else { return nil }
        return ISO8601DateFormatter().date(from: str)
    }
}

/// Response from GET /billing/subscription
struct SubscriptionResponse: Codable, Sendable {
    let hasSubscription: Bool
    let subscription: SubscriptionDetails?

    enum CodingKeys: String, CodingKey {
        case hasSubscription = "has_subscription"
        case subscription
    }

    struct SubscriptionDetails: Codable, Sendable {
        let id: String
        let tier: String
        let status: String
        let productId: String
        let expiresAt: String?
        let autoRenewEnabled: Bool
        let isInGracePeriod: Bool
        let createdAt: String

        enum CodingKeys: String, CodingKey {
            case id, tier, status
            case productId = "product_id"
            case expiresAt = "expires_at"
            case autoRenewEnabled = "auto_renew_enabled"
            case isInGracePeriod = "is_in_grace_period"
            case createdAt = "created_at"
        }
    }
}

/// Response from POST /billing/trial/activate
struct ActivateTrialResponse: Codable, Sendable {
    let success: Bool
    let songsGranted: Int
    let songsRemaining: Int
    let trialExpiresAt: String
    let durationDays: Int

    enum CodingKeys: String, CodingKey {
        case success
        case songsGranted = "songs_granted"
        case songsRemaining = "songs_remaining"
        case trialExpiresAt = "trial_expires_at"
        case durationDays = "duration_days"
    }

    /// Parse trial expiration date
    var trialExpiresAtDate: Date? {
        ISO8601DateFormatter().date(from: trialExpiresAt)
    }
}

/// Response from GET /billing/plans
struct PlansResponse: Codable, Sendable {
    let plans: [SubscriptionPlan]
}

/// A subscription plan from the backend
struct SubscriptionPlan: Codable, Sendable, Identifiable {
    let id: String
    let name: String
    let tier: String
    let songsPerMonth: Int
    let previewsPerDay: Int
    let priceMonthly: Int?
    let priceAnnual: Int?
    let description: String?
    let features: [String]
    let isActive: Bool
    let sortOrder: Int

    enum CodingKeys: String, CodingKey {
        case id, name, tier, description, features
        case songsPerMonth = "songs_per_month"
        case previewsPerDay = "previews_per_day"
        case priceMonthly = "price_monthly_cents"
        case priceAnnual = "price_annual_cents"
        case isActive = "is_active"
        case sortOrder = "sort_order"
    }

    /// Format price in dollars
    func formattedMonthlyPrice() -> String {
        guard let cents = priceMonthly else { return "Free" }
        return String(format: "$%.2f", Double(cents) / 100.0)
    }

    func formattedAnnualPrice() -> String {
        guard let cents = priceAnnual else { return "Free" }
        return String(format: "$%.2f", Double(cents) / 100.0)
    }
}

// MARK: - Occasions

/// Available occasions
enum Occasion: String, CaseIterable, Identifiable, Sendable {
    case birthday = "birthday"
    case anniversary = "anniversary"
    case thankYou = "thank_you"
    case iLoveYou = "i_love_you"
    case wedding = "wedding"
    case graduation = "graduation"
    case celebration = "celebration"
    case apology = "apology"
    case encouragement = "encouragement"
    case custom = "custom"

    var id: String { rawValue }

    var displayName: String {
        switch self {
        case .birthday: return "Birthday"
        case .anniversary: return "Anniversary"
        case .thankYou: return "Thank You"
        case .iLoveYou: return "I Love You"
        case .wedding: return "Wedding"
        case .graduation: return "Graduation"
        case .celebration: return "Celebration"
        case .apology: return "Apology"
        case .encouragement: return "Encouragement"
        case .custom: return "Custom"
        }
    }

    var emoji: String {
        switch self {
        case .birthday: return "🎂"
        case .anniversary: return "💑"
        case .thankYou: return "🙏"
        case .iLoveYou: return "❤️"
        case .wedding: return "💒"
        case .graduation: return "🎓"
        case .celebration: return "🎉"
        case .apology: return "💐"
        case .encouragement: return "💪"
        case .custom: return "✨"
        }
    }
}
